In [1]:
import pandas as pd

In [3]:
df = pd.read_csv('core_dataset.csv')

In [4]:
df

,Employee Name,Employee Number,State,Zip,DOB,Age,Sex,MaritalDesc,CitizenDesc,Hispanic/Latino,...,Date of Hire,Date of Termination,Reason For Term,Employment Status,Department,Position,Pay Rate,Manager Name,Employee Source,Performance Score
0,"Brown, Mia",1.103024e+09,MA,1450.0,11/24/1985,32.0,Female,Married,US Citizen,No,...,10/27/2008,NaN,N/A - still employed,Active,Admin Offices,Accountant I,28.50,Brandon R. LeBlanc,Diversity Job Fair,Fully Meets
1,"LaRotonda, William",1.106027e+09,MA,1460.0,4/26/1984,33.0,Male,Divorced,US Citizen,No,...,1/6/2014,NaN,N/A - still employed,Active,Admin Offices,Accountant I,23.00,Brandon R. LeBlanc,Website Banner Ads,Fully Meets
2,"Steans, Tyrone",1.302053e+09,MA,2703.0,9/1/1986,31.0,Male,Single,US Citizen,No,...,9/29/2014,NaN,N/A - still employed,Active,Admin Offices,Accountant I,29.00,Brandon R. LeBlanc,Internet Search,Fully Meets
3,"Howard, Estelle",1.211051e+09,MA,2170.0,9/16/1985,32.0,Female,Married,US Citizen,No,...,2/16/2015,4/15/2015,N/A - still employed,Active,Admin Offices,Administrative Assistant,21.50,Brandon R. LeBlanc,Pay Per Click - Google,N/A- too early to review
4,"Singh, Nan",1.307060e+09,MA,2330.0,5/19/1988,29.0,Female,Single,US Citizen,No,...,5/1/2015,NaN,N/A - still employed,Active,Admin Offices,Administrative Assistant,16.56,Brandon R. LeBlanc,Website Banner Ads,N/A- too early to review
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
297,"Saada, Adell",1.012023e+09,MA,2132.0,7/24/1986,31.0,Female,Married,US Citizen,No,...,11/5/2012,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,49.25,Alex Sweetwater,Pay Per Click - Google,Fully Meets
298,"Szabo, Andrew",1.201031e+09,MA,2140.0,5/6/1983,34.0,Male,Single,US Citizen,No,...,7/7/2014,NaN,N/A - still employed,Active,Software Engineering,Software Engineer,48.00,Alex Sweetwater,MBTA ads,Exceptional
299,"True, Edward",1.102024e+09,MA,2451.0,6/14/1983,34.0,Male,Single,Non-Citizen,No,...,2/18/2013,4/15/2014,medical issues,Voluntarily Terminated,Software Engineering,Software Engineer,45.42,Alex Sweetwater,Diversity Job Fair,Fully Meets
300,"Sweetwater, Alex",1.001645e+09,MA,2184.0,11/22/1966,51.0,Male,Single,US Citizen,No,...,8/15/2011,NaN,N/A - still employed,Active,Software Engineering,Software Engineering Manager,27.00,Jennifer Zamora,Search Engine - Google Bing Yahoo,Fully Meets
301,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 302 entries, 0 to 301
Data columns (total 21 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   Employee Name        301 non-null    object
 1   Employee Number      301 non-null    float64
 2   State                301 non-null    object
 3   Zip                  301 non-null    float64
 4   DOB                  301 non-null    object
 5   Age                  301 non-null    float64
 6   Sex                  301 non-null    object
 7   MaritalDesc          301 non-null    object
 8   CitizenDesc          301 non-null    object
 9   Hispanic/Latino      301 non-null    object
 10  RaceDesc             301 non-null    object
 11  Date of Hire         301 non-null    object
 12  Date of Termination  103 non-null    object
 13  Reason For Term      301 non-null    object
 14  Employment Status    301 non-null    object
 15  Department           301 non-null    object
 16  Position             301 non-null    object
 17  Pay Rate             301 non-null    float64
 18  Manager Name         301 non-null    object
 19  Employee Source      301 non-null    object
 20  Performance Score    301 non-null    object
dtypes: float64(4), object(17)
memory usage: 49.7+ KB

In [8]:
!pip install pivottablejs

Collecting pivottablejs
  Downloading pivottablejs-0.9.0-py2.py3-none-any.whl (4.7 kB)
Installing collected packages: pivottablejs
Successfully installed pivottablejs-0.9.0

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

In [9]:
from pivottablejs import pivot_ui

In [12]:
df.shape

(302, 21)

In [10]:
pivot_ui(df)

In [16]:
!pip install pandasgui

Collecting pandasgui

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [12 lines of output]
  OSError: [Errno 9] Bad file descriptor

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\atyra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\atyra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 349, in main
      write_json(json_out, pjoin(control_dir, 'output.json'), indent=2)
    File "C:\Users\atyra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 31, in write_json
      with open(path, 'w', encoding='utf-8') as f:
  OSError: [Errno 9] Bad file descriptor
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: python.exe -m pip install --upgrade pip

  Using cached pandasgui-0.2.14.tar.gz (218 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

In [20]:
pip install --upgrade pip

Requirement already satisfied: pip in c:\users\atyra\appdata\local\programs\python\python312\lib\site-packages (23.3.2)
Collecting pip
  Downloading pip-24.0-py3-none-any.whl.metadata (3.6 kB)
Downloading pip-24.0-py3-none-any.whl (2.1 MB)
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
   ---------------------------------------- 0.0/2.1 MB ? eta -:--:--
    --------------------------------------- 0.0/2.1 MB 326.8 kB/s eta 0:00:07
   - -------------------------------------- 0.1/2.1 MB 581.0 kB/s eta 0:00:04
   -- ------------------------------------- 0.2/2.1 MB 833.5 kB/s eta 0:00:03
   ---- ----------------------------------- 0.2/2.1 MB 958.6 kB/s eta 0:00:02
   ------- -------------------------------- 0.4/2.1 MB 1.4 MB/s eta 0:00:02
   ---------- ----------------------------- 0.6/2.1 MB 1.7 MB/s eta 0:00:01
   ---------------- ----------------------- 0.9/2.1 MB 2.3 MB/s eta 0:00:01
   -------------------- ------------------- 1.1/2.1 MB 2.5 MB/s eta 0:00:01
   ------------------------ --------------- 1.3/2.1 MB 2.8 MB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 3.1 MB/s eta 0:00:01
   ------------------------------ --------- 1.6/2.1 MB 3.1 MB/s eta 0:00:01
   --------------------------------- ------ 1.8/2.1 MB 2.9 MB/s eta 0:00:01
   ---------------------------------------  2.1/2.1 MB 3.3 MB/s eta 0:00:01
   ---------------------------------------- 2.1/2.1 MB 3.1 MB/s eta 0:00:00
Installing collected packages: pip
  Attempting uninstall: pip
    Found existing installation: pip 23.3.2
    Uninstalling pip-23.3.2:
      Successfully uninstalled pip-23.3.2
Successfully installed pip-24.0
Note: you may need to restart the kernel to use updated packages.

In [2]:
!pip install pandasgui

Collecting pandasgui
  Using cached pandasgui-0.2.14.tar.gz (218 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'

  error: subprocess-exited-with-error

  Getting requirements to build wheel did not run successfully.
  exit code: 1

  [12 lines of output]
  OSError: [Errno 9] Bad file descriptor

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "C:\Users\atyra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
      main()
    File "C:\Users\atyra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 349, in main
      write_json(json_out, pjoin(control_dir, 'output.json'), indent=2)
    File "C:\Users\atyra\AppData\Local\Programs\Python\Python312\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 31, in write_json
      with open(path, 'w', encoding='utf-8') as f:
  OSError: [Errno 9] Bad file descriptor
  [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

Getting requirements to build wheel did not run successfully.
exit code: 1

See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

In [3]:
from pandasgui import show

ModuleNotFoundError: No module named 'pandasgui'

In [4]:
show(df)

NameError: name 'show' is not defined